### ISSUE TITLE
Add CI support

### ISSUE THREAD

**Issue by uilianries** [conan-io/examples#4]
It would be nice add Linux, MacOS and Windows CI jobs to reproduce all steps required to build the example.

**Comment by jgsogo** [comment]
About CI, do we need `build.py` files? I think it could be easier regarding the docs _"If you are insterested to reproduce examples in your enviroment, please **follow the CI scripts**"_ to provide `sh`, `bat` files with raw commands (those would allow copy/paste for end users).

I think it is possible to implement it both in travis and appveyor:

travis
```
matrix:
   include:
      - stage: Conan Workspaces
        <<: *linux
        script:
          - ./features/workspace/cmake/build.sh
```

appveyor
```
environment:
    PYTHON: "C:\\Python37"

     matrix:
        # Conan Workspaces
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
          BUILD_SCRIPT: features/workspace/cmake/build_XXXX.bat

...

test_script:
  - %BUILD_SCRIPT%
```

I'm just suggesting it, do you think it makes sense?
